// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basemsg.proto

package com.zy.nut.relayer.common.beans.pb;

public final class Basemsg {
  private Basemsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zy.nut.relayer.common.beans.pb.BaseMsgPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 mid = 1;</code>
     */
    long getMid();

    /**
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int64 ctime = 3;</code>
     */
    long getCtime();

    /**
     * <code>int64 lctime = 4;</code>
     */
    long getLctime();
  }
  /**
   * Protobuf type {@code com.zy.nut.relayer.common.beans.pb.BaseMsgPB}
   */
  public  static final class BaseMsgPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zy.nut.relayer.common.beans.pb.BaseMsgPB)
      BaseMsgPBOrBuilder {
    // Use BaseMsgPB.newBuilder() to construct.
    private BaseMsgPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsgPB() {
      mid_ = 0L;
      msg_ = "";
      ctime_ = 0L;
      lctime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseMsgPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              mid_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              ctime_ = input.readInt64();
              break;
            }
            case 32: {

              lctime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.nut.relayer.common.beans.pb.Basemsg.internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.nut.relayer.common.beans.pb.Basemsg.internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.class, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder.class);
    }

    public static final int MID_FIELD_NUMBER = 1;
    private long mid_;
    /**
     * <code>int64 mid = 1;</code>
     */
    public long getMid() {
      return mid_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTIME_FIELD_NUMBER = 3;
    private long ctime_;
    /**
     * <code>int64 ctime = 3;</code>
     */
    public long getCtime() {
      return ctime_;
    }

    public static final int LCTIME_FIELD_NUMBER = 4;
    private long lctime_;
    /**
     * <code>int64 lctime = 4;</code>
     */
    public long getLctime() {
      return lctime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mid_ != 0L) {
        output.writeInt64(1, mid_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (ctime_ != 0L) {
        output.writeInt64(3, ctime_);
      }
      if (lctime_ != 0L) {
        output.writeInt64(4, lctime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, mid_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (ctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ctime_);
      }
      if (lctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lctime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB)) {
        return super.equals(obj);
      }
      com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB other = (com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB) obj;

      boolean result = true;
      result = result && (getMid()
          == other.getMid());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getCtime()
          == other.getCtime());
      result = result && (getLctime()
          == other.getLctime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMid());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + CTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCtime());
      hash = (37 * hash) + LCTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLctime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zy.nut.relayer.common.beans.pb.BaseMsgPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zy.nut.relayer.common.beans.pb.BaseMsgPB)
        com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.nut.relayer.common.beans.pb.Basemsg.internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.nut.relayer.common.beans.pb.Basemsg.internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.class, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder.class);
      }

      // Construct using com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mid_ = 0L;

        msg_ = "";

        ctime_ = 0L;

        lctime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.nut.relayer.common.beans.pb.Basemsg.internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor;
      }

      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getDefaultInstanceForType() {
        return com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.getDefaultInstance();
      }

      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB build() {
        com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB buildPartial() {
        com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB result = new com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB(this);
        result.mid_ = mid_;
        result.msg_ = msg_;
        result.ctime_ = ctime_;
        result.lctime_ = lctime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB) {
          return mergeFrom((com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB other) {
        if (other == com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.getDefaultInstance()) return this;
        if (other.getMid() != 0L) {
          setMid(other.getMid());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getCtime() != 0L) {
          setCtime(other.getCtime());
        }
        if (other.getLctime() != 0L) {
          setLctime(other.getLctime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long mid_ ;
      /**
       * <code>int64 mid = 1;</code>
       */
      public long getMid() {
        return mid_;
      }
      /**
       * <code>int64 mid = 1;</code>
       */
      public Builder setMid(long value) {
        
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mid = 1;</code>
       */
      public Builder clearMid() {
        
        mid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private long ctime_ ;
      /**
       * <code>int64 ctime = 3;</code>
       */
      public long getCtime() {
        return ctime_;
      }
      /**
       * <code>int64 ctime = 3;</code>
       */
      public Builder setCtime(long value) {
        
        ctime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ctime = 3;</code>
       */
      public Builder clearCtime() {
        
        ctime_ = 0L;
        onChanged();
        return this;
      }

      private long lctime_ ;
      /**
       * <code>int64 lctime = 4;</code>
       */
      public long getLctime() {
        return lctime_;
      }
      /**
       * <code>int64 lctime = 4;</code>
       */
      public Builder setLctime(long value) {
        
        lctime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lctime = 4;</code>
       */
      public Builder clearLctime() {
        
        lctime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.zy.nut.relayer.common.beans.pb.BaseMsgPB)
    }

    // @@protoc_insertion_point(class_scope:com.zy.nut.relayer.common.beans.pb.BaseMsgPB)
    private static final com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB();
    }

    public static com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsgPB>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsgPB>() {
      public BaseMsgPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseMsgPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsgPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsgPB> getParserForType() {
      return PARSER;
    }

    public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbasemsg.proto\022\"com.zy.nut.relayer.comm" +
      "on.beans.pb\"D\n\tBaseMsgPB\022\013\n\003mid\030\001 \001(\003\022\013\n" +
      "\003msg\030\002 \001(\t\022\r\n\005ctime\030\003 \001(\003\022\016\n\006lctime\030\004 \001(" +
      "\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zy_nut_relayer_common_beans_pb_BaseMsgPB_descriptor,
        new java.lang.String[] { "Mid", "Msg", "Ctime", "Lctime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
