// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roommsg.proto

package com.zy.nut.relayer.common.beans.pb;

public final class Roommsg {
  private Roommsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomMsgPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zy.nut.relayer.common.beans.pb.RoomMsgPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    boolean hasBaseMsg();
    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getBaseMsg();
    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder getBaseMsgOrBuilder();

    /**
     * <code>int64 fuid = 2;</code>
     */
    long getFuid();

    /**
     * <code>int64 rid = 3;</code>
     */
    long getRid();
  }
  /**
   * Protobuf type {@code com.zy.nut.relayer.common.beans.pb.RoomMsgPB}
   */
  public  static final class RoomMsgPB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zy.nut.relayer.common.beans.pb.RoomMsgPB)
      RoomMsgPBOrBuilder {
    // Use RoomMsgPB.newBuilder() to construct.
    private RoomMsgPB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomMsgPB() {
      fuid_ = 0L;
      rid_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoomMsgPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder subBuilder = null;
              if (baseMsg_ != null) {
                subBuilder = baseMsg_.toBuilder();
              }
              baseMsg_ = input.readMessage(com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseMsg_);
                baseMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              fuid_ = input.readInt64();
              break;
            }
            case 24: {

              rid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zy.nut.relayer.common.beans.pb.Roommsg.internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zy.nut.relayer.common.beans.pb.Roommsg.internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.class, com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.Builder.class);
    }

    public static final int BASEMSG_FIELD_NUMBER = 1;
    private com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB baseMsg_;
    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    public boolean hasBaseMsg() {
      return baseMsg_ != null;
    }
    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getBaseMsg() {
      return baseMsg_ == null ? com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.getDefaultInstance() : baseMsg_;
    }
    /**
     * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
     */
    public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder getBaseMsgOrBuilder() {
      return getBaseMsg();
    }

    public static final int FUID_FIELD_NUMBER = 2;
    private long fuid_;
    /**
     * <code>int64 fuid = 2;</code>
     */
    public long getFuid() {
      return fuid_;
    }

    public static final int RID_FIELD_NUMBER = 3;
    private long rid_;
    /**
     * <code>int64 rid = 3;</code>
     */
    public long getRid() {
      return rid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseMsg_ != null) {
        output.writeMessage(1, getBaseMsg());
      }
      if (fuid_ != 0L) {
        output.writeInt64(2, fuid_);
      }
      if (rid_ != 0L) {
        output.writeInt64(3, rid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseMsg());
      }
      if (fuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fuid_);
      }
      if (rid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB)) {
        return super.equals(obj);
      }
      com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB other = (com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB) obj;

      boolean result = true;
      result = result && (hasBaseMsg() == other.hasBaseMsg());
      if (hasBaseMsg()) {
        result = result && getBaseMsg()
            .equals(other.getBaseMsg());
      }
      result = result && (getFuid()
          == other.getFuid());
      result = result && (getRid()
          == other.getRid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseMsg()) {
        hash = (37 * hash) + BASEMSG_FIELD_NUMBER;
        hash = (53 * hash) + getBaseMsg().hashCode();
      }
      hash = (37 * hash) + FUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFuid());
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zy.nut.relayer.common.beans.pb.RoomMsgPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zy.nut.relayer.common.beans.pb.RoomMsgPB)
        com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zy.nut.relayer.common.beans.pb.Roommsg.internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zy.nut.relayer.common.beans.pb.Roommsg.internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.class, com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.Builder.class);
      }

      // Construct using com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseMsgBuilder_ == null) {
          baseMsg_ = null;
        } else {
          baseMsg_ = null;
          baseMsgBuilder_ = null;
        }
        fuid_ = 0L;

        rid_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zy.nut.relayer.common.beans.pb.Roommsg.internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor;
      }

      public com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB getDefaultInstanceForType() {
        return com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.getDefaultInstance();
      }

      public com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB build() {
        com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB buildPartial() {
        com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB result = new com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB(this);
        if (baseMsgBuilder_ == null) {
          result.baseMsg_ = baseMsg_;
        } else {
          result.baseMsg_ = baseMsgBuilder_.build();
        }
        result.fuid_ = fuid_;
        result.rid_ = rid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB) {
          return mergeFrom((com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB other) {
        if (other == com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB.getDefaultInstance()) return this;
        if (other.hasBaseMsg()) {
          mergeBaseMsg(other.getBaseMsg());
        }
        if (other.getFuid() != 0L) {
          setFuid(other.getFuid());
        }
        if (other.getRid() != 0L) {
          setRid(other.getRid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB baseMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder> baseMsgBuilder_;
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public boolean hasBaseMsg() {
        return baseMsgBuilder_ != null || baseMsg_ != null;
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB getBaseMsg() {
        if (baseMsgBuilder_ == null) {
          return baseMsg_ == null ? com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.getDefaultInstance() : baseMsg_;
        } else {
          return baseMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public Builder setBaseMsg(com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB value) {
        if (baseMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseMsg_ = value;
          onChanged();
        } else {
          baseMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public Builder setBaseMsg(
          com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder builderForValue) {
        if (baseMsgBuilder_ == null) {
          baseMsg_ = builderForValue.build();
          onChanged();
        } else {
          baseMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public Builder mergeBaseMsg(com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB value) {
        if (baseMsgBuilder_ == null) {
          if (baseMsg_ != null) {
            baseMsg_ =
              com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.newBuilder(baseMsg_).mergeFrom(value).buildPartial();
          } else {
            baseMsg_ = value;
          }
          onChanged();
        } else {
          baseMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public Builder clearBaseMsg() {
        if (baseMsgBuilder_ == null) {
          baseMsg_ = null;
          onChanged();
        } else {
          baseMsg_ = null;
          baseMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder getBaseMsgBuilder() {
        
        onChanged();
        return getBaseMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      public com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder getBaseMsgOrBuilder() {
        if (baseMsgBuilder_ != null) {
          return baseMsgBuilder_.getMessageOrBuilder();
        } else {
          return baseMsg_ == null ?
              com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.getDefaultInstance() : baseMsg_;
        }
      }
      /**
       * <code>.com.zy.nut.relayer.common.beans.pb.BaseMsgPB baseMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder> 
          getBaseMsgFieldBuilder() {
        if (baseMsgBuilder_ == null) {
          baseMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPB.Builder, com.zy.nut.relayer.common.beans.pb.Basemsg.BaseMsgPBOrBuilder>(
                  getBaseMsg(),
                  getParentForChildren(),
                  isClean());
          baseMsg_ = null;
        }
        return baseMsgBuilder_;
      }

      private long fuid_ ;
      /**
       * <code>int64 fuid = 2;</code>
       */
      public long getFuid() {
        return fuid_;
      }
      /**
       * <code>int64 fuid = 2;</code>
       */
      public Builder setFuid(long value) {
        
        fuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fuid = 2;</code>
       */
      public Builder clearFuid() {
        
        fuid_ = 0L;
        onChanged();
        return this;
      }

      private long rid_ ;
      /**
       * <code>int64 rid = 3;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>int64 rid = 3;</code>
       */
      public Builder setRid(long value) {
        
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rid = 3;</code>
       */
      public Builder clearRid() {
        
        rid_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.zy.nut.relayer.common.beans.pb.RoomMsgPB)
    }

    // @@protoc_insertion_point(class_scope:com.zy.nut.relayer.common.beans.pb.RoomMsgPB)
    private static final com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB();
    }

    public static com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomMsgPB>
        PARSER = new com.google.protobuf.AbstractParser<RoomMsgPB>() {
      public RoomMsgPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoomMsgPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomMsgPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomMsgPB> getParserForType() {
      return PARSER;
    }

    public com.zy.nut.relayer.common.beans.pb.Roommsg.RoomMsgPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rroommsg.proto\022\"com.zy.nut.relayer.comm" +
      "on.beans.pb\032\rbasemsg.proto\"f\n\tRoomMsgPB\022" +
      ">\n\007baseMsg\030\001 \001(\0132-.com.zy.nut.relayer.co" +
      "mmon.beans.pb.BaseMsgPB\022\014\n\004fuid\030\002 \001(\003\022\013\n" +
      "\003rid\030\003 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zy.nut.relayer.common.beans.pb.Basemsg.getDescriptor(),
        }, assigner);
    internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zy_nut_relayer_common_beans_pb_RoomMsgPB_descriptor,
        new java.lang.String[] { "BaseMsg", "Fuid", "Rid", });
    com.zy.nut.relayer.common.beans.pb.Basemsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
